# yaml 配置
services:
  cuda:
    build: .
    command: [ "bash", "./run.sh" ]
    environment:
      all_proxy: http://host.docker.internal:7890
      http_proxy: http://host.docker.internal:7890
      https_proxy: http://host.docker.internal:7890
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # ports:
    #   - "7890:7890"
    volumes:
      - .:${DIR}:rw
    working_dir: ${DIR}
version: '3'
